#!/usr/bin/env python

##############################################################################
#
# NAME:        manage.py
#
# FACILITY:    SAM (Service Availability Monitoring)
#
# COPYRIGHT:
#         Copyright (c) 2009, Members of the EGEE Collaboration.
#         http://www.eu-egee.org/partners/
#         Licensed under the Apache License, Version 2.0.
#         http://www.apache.org/licenses/LICENSE-2.0
#         This software is provided "as is", without warranties
#         or conditions of any kind, either express or implied.
#
# DESCRIPTION:
#
#         
#
# AUTHORS:     Vibhuti Duggal, BARC
#
# CREATED:     6-Jul-2012
#
# NOTES:
#
# MODIFIED:
#
##############################################################################

from django.core.management import execute_manager
try:
    import atp.settings # Assumed to be in the same directory.
except ImportError:
    import sys
    sys.stderr.write("Error: Can't find the file 'atp.settings.py' in the directory containing %r. It appears you've customized things.\nYou'll have to run django-admin.py, passing it your atp.settings module.\n(If the file atp.settings.py does indeed exist, it's causing an ImportError somehow.)\n" % __file__)
    sys.exit(1)

if __name__ == "__main__":
    execute_manager(atp.settings)
